### ISSUE TITLE
Nextcloud Talk Signaling API

### ISSUE THREAD

**Issue by markuman** [saltyrtc/saltyrtc-server-python#119]
Any change that saltyrtc can support the nextcloud talk signaling api?  
https://nextcloud-talk.readthedocs.io/en/latest/standalone-signaling-api-v1/

When I try to let nextcloud talk fire on saltyrtc, it requests for `/spreed`, which seems not be available.

```
Request URL:wss://coturn.osuv.de:8765/spreed
Request Method:GET
Remote Address:78.47.44.230:8765
Status Code:
101
Version:HTTP/1.1
```

**Comment by lgrahl** [comment]
I think you will have to elaborate because I'm at a complete loss on what you're trying to achieve. :woman_shrugging:

**Comment by markuman** [comment]
@lgrahl Ok, maybe yes - I am completely wrong :)

Nextcloud Talk is an App of Nextcloud, which is based on WebRTC

> We’re not reinventing the wheel! Based on the great simpleWebRTC library.  
https://github.com/nextcloud/spreed

In general they say that their implementation can handle around 4  (+/- 2) participants using video chat - based on your CPU (decode of every single video stream of every participants) and upload bandwidth (sending your own video stream of every single participants - because it's p2p).

In their settings mode, they say, when you need video chat with more people, you need an "external signaling server".  
Here is a screenshot of that part:
 
![Screenshot_2020-04-27 Settings - Nextcloud](https://user-images.githubusercontent.com/3920157/80400423-10c79a80-88bb-11ea-9477-a1ef388056aa.png)

So I'm trying to achieve that. Setup an external signaling server for nextcloud talk.  
...and my thought is, that SaltyRTC is one of that? Isn't it?

**Comment by dbrgn** [comment]
You're probably coming from https://help.nextcloud.com/t/signaling-server-recommendations/52798/13?

No, SaltyRTC is not a "Nextcloud signaling server", it's simply a framework for building your own application signaling. I assume a signaling server would require specific support for Nextcloud in order to work properly. Furthermore, SaltyRTC only does signaling and does not act as a SFU / MCU, it's not designed to handle/manage video streams.

Check out https://github.com/nextcloud/spreed/issues/2515 It seems that right now you'll have to go with their commercial offering since no other solutions seem to be supported (intentionally?).

**Comment by lgrahl** [comment]
I guess the term "signalling" isn't that well defined. :slightly_smiling_face:

Quite off-topic, but: For now, there's probably no way around self-hosted Jitsi if you don't want to spread your voice and video data onto some other person's servers but still have a reasonable amount of people in your conference call. Personally, not being able to self-host with the NC solution is a deal-breaker to me.
